### PR TITLE
sqVirtualMachine.{c,h} doesn't need execute permission.

### PR DESCRIPTION
**Pull request by takano32**
`chmod 644 sqVirtualMachine.{c,h}`

### CODE REVIEW

**Comment by takano32** [comment]
Would you merge  this?
or Is there something wrong for this PR?
@estebanlm

**Comment by estebanlm** [comment]
I was on holidays :)
I didn't check vm pull requests yet, sorry... I will do this days.

**Comment by estebanlm** [comment]
this one looks easy enough :P

**Comment by takano32** [comment]
Thanks for your merge!
And I'm sorry for little tirivial fix. :bow: 

I want to test merge process is correct or not by this PR.
I'll make more difficult PR in future. :-)

**Pull request merged**
