### PR TITLE
Issue13199 

### PR DESCRIPTION
**Pull request by nicolas-cellier-aka-nice**
My first correction was wrong because it was reverting a bugfix.
But the original bugfix was suspect too and deserves a new attempt.
See https://github.com/pharo-project/pharo-vm/commit/7f3f991283344d4cf0aa6a50b8615416062ec381
So I reopened https://pharo.fogbugz.com/f/cases/13199/Stinky-argument-inversion-of-atomic-swap-MACRO-for-iphone-gcc-branch
And I'm proposing this one - let's cross fingers...

### CODE REVIEW

**Comment by estebanlm** [comment]
I don't know the end of this issue. Reverting was not enough but I do not see other changes... I'm missing something?

**Comment by nicolas-cellier-aka-nice** [comment]
My "fix" mostly work. However there's a bigger problem with the root code: sqCompareAndSwapRes is not truly atomic and thus can screw you. I've modified the code further, advertised on vm-dev - see solution sketch at http://article.gmane.org/gmane.comp.lang.smalltalk.squeak.vm.devel/12832/match=sqCompareAndSwapRes , and sent a private copy of patch to Eliot. When he has time, he will have a look.

**Comment by takano32** [comment]
This PR may be no longer needed (and too old).

ref. https://pharo.fogbugz.com/f/cases/13199/Stinky-argument-inversion-of-atomic-swap-MACRO-for-iphone-gcc-branch

Would someone be able to close this PR?

**Comment by nicolas-cellier-aka-nice** [comment]
done.

Shouldn't new contributions be on opensmalltalk-vm?

2016-09-30 9:16 GMT+02:00 TAKANO Mitsuhiro notifications@github.com:

**Comment by estebanlm** [comment]
yes... for now I'm merging back this contributions because our new process is still not in production.

**Pull request closed without merging**
