### PR TITLE
Updated Cairo to 1.15.2

### PR DESCRIPTION
**Pull request by syrel**
updated cairo to latest     'cairo-1.15.2' version.
added '--enable-gl' compilation flag to support hardware acceleration

### CODE REVIEW

**Comment by syrel** [comment]
with '--enable-gl' fails to compile on mac. Anyway OpenGL support with cairo on mac is bad. We either need NSOpenGL(needs additional plugin and custom cairo) or GLX (forces users to install X11).

Anyway cairo update would be nice.

**Comment by estebanlm** [comment]
I will rollback this change because it does not compiles on Windows and I don't know how to make it work. 
I also think removing --enable-gl from compilation can cause problems, in particular for @ronsaldo and all other people working precisely on OpenGL (but no idea how this affects them)

**Comment by ronsaldo** [comment]
I do not care about the Cairo OpenGL support. We are not using Cairo OpenGL
with Woden.

2016-04-27 10:59 GMT+02:00 Esteban Lorenzano notifications@github.com:

**Comment by PharoProject** [comment]
ok, then going without opengl is a possible path :)

**Pull request merged**
