### PR TITLE
Initial commit for X11 display plugin and new display model.

### PR DESCRIPTION
**Pull request by ronsaldo**
Conflicts:
    mc/CMakeVMMaker.package/monticello.meta/version
    mc/VMMaker-oscog.package/monticello.meta/version

### CODE REVIEW

**Comment by ronsaldo** [comment]
This does not make sense to integrate right now. Only Linux new display is implemented.

**Comment by estebanlm** [comment]
why don’t you work on a branch?

**Comment by camillobruni** [comment]
actually this is more for documentation :P
and to see that everything is properly set up in ronie's fork

**Comment by sig** [comment]
don't pull it. new vm are not compatible with current images.

On 16 January 2014 15:30, Camillo Bruni notifications@github.com wrote:

> actually this is more for documentation :P
> and to see that everything is properly set up in ronie's fork
> 
> On 2014-01-16, at 15:28, Esteban Lorenzano notifications@github.com
> wrote:
> 
> > why don’t you work on a branch?
> > 
> > On 16 Jan 2014, at 15:27, ronsaldo notifications@github.com wrote:
> > 
> > > This does not make sense to integrate right now. Only Linux new
> > > display is implemented.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pharo-project/pharo-vm/pull/11#issuecomment-32473067
> .

## 

Best regards,
Igor Stasenko.

**Comment by estebanlm** [comment]
another good reason to use a branch :)

**Comment by camillobruni** [comment]
so lets close this and keep it for later ;)

**Pull request closed without merging**
