### PR TITLE
Allow to open a FileStream based on fd or FILE*

### PR DESCRIPTION
**Pull request by zecke**
Add new primitives so we can use Unix FDs with the AIO Plugin. The FILE* will be opened as byte stream. On Unix this doesn't make a difference.

### CODE REVIEW

**Comment by zecke** [comment]
AppVeyor failed because it couldn't download libpng. How can we retry the build? It would be nice to get this primitive in for Pharo7.

**Comment by estebanlm** [comment]
I need to pull changes from opensmalltalk-vm where this was fixed.

**Comment by zecke** [comment]
ping?

**Comment by estebanlm** [comment]
pong, sorry I forget about it.
I'm now in holidays (bah... half holidays half "smalltalks 2017"). 
can you remind me again the week of 20/11 (I will integrate it, but since is VMMaker related I need to do it by hand)

**Review by estebanlm — APPROVED** [review]

**Comment by zecke** [comment]
Enjoy! Will ping you again.

**Comment by akgrant43** [comment]
I can make the changes in VMMaker (as opposed to pharo-vm), which should get this in to the VM.

@zecke I assume that nothing has changed since you submitted this, right?

Cheers,
Alistair

**Comment by estebanlm** [comment]
I was going to apply the merge myself, but if you have the time, please go ahead :)

**Comment by estebanlm** [comment]
(yep, this took a lot of time because when I was about to do it, everything was broken and I needed to restore the VM building for pharo... which I finished -hopefully- yesterday ;) )

**Comment by akgrant43** [comment]
> I was going to apply the merge myself, but if you have the time, please go ahead :)

No problem.

Especially if it helps get a new linux 32 bit VM that includes FileAttributesPlugin released to stable (i.e. anything from early Feb onwards).  I'll need it to be able to update the bootstrap process.  Hint Hint. :-) :-) :-)

**Comment by akgrant43** [comment]
@zecke can you also point me to the associated changes to FilePluginPrims?

**Comment by estebanlm** [comment]
there are none. 
the advantage of having all in same place is that a PR is complete, no need to do magic searchs :)

**Comment by estebanlm** [comment]
I mean, there none outside what you are seeing :)

**Comment by akgrant43** [comment]
OK, I'll do a bit of reverse engineering.

It looks like I should open a fogbugz issue as well.

**Comment by zecke** [comment]
For inotify and maybe long-term SCTP support (I don't give up).. having something like a "socket notifier" that integrates with the eventloop/aio code would be nice too.

The patch I presented is needed as well for other usecases.

**Comment by akgrant43** [comment]
@zecke The VMs on bintray at:

https://bintray.com/opensmalltalk/vm/cog/201803031106#files

include the two additional primitives in FilePlugin.

The extensions to FilePlugin are at:

https://github.com/akgrant43/AKG-FileSystem

I haven't written a BaselineOf yet, so you'll need to clone it in Iceberg and load the single package.

I'll convert the smalltalk code to a PR after the VM makes it to vmLatest.

The issue is being tracked at: 

https://pharo.fogbugz.com/f/cases/21462/Open-a-FileStream-based-on-fd-or-FILE
https://github.com/OpenSmalltalk/opensmalltalk-vm/pull/222

**Comment by zecke** [comment]
Cool! Do you know git commit --author? Maybe I am just hungry right now but I would have appreciated if my name is somehow attached to work I started. ;)

**Comment by zecke** [comment]
Cool! Maybe I have a shot in getting a non-blocking/non-polling SCTP support into the image.

**Comment by jecisc** [comment]
Hi,

Can you describe a little what possibilities this PR will bring to Pharo to someone who have no system knowlegde?

No need for a long explanation, but something fast would be cool :)

**Comment by zecke** [comment]
> On 3. Mar 2018, at 14:59, CyrilFerlicot <notifications@github.com> wrote:
> 
> Hi,
> 
> Can you describe a little what possibilities this PR will bring to Pharo to someone who have no system knowlegde?
> 
> No need for a long explanation, but something fast would be cool :)

The original code/motivation is here: http://forum.world.st/Using-a-Unix-filedescriptor-in-a-FileStream-td4916353.html

OSSubProcess can use this primitive

One can use alien to create an inotify descriptor, epoll, sctp fd and have non-blocking IO (through he AIO module). Now that we finally have this integrated, we can do more nice things from the image. The alternative was to poll (create a process that checks every n-ms if there was an event.. bad latency and more cpu usage are the result).


holger

**Comment by jecisc** [comment]
Thank you!

**Comment by marianopeck** [comment]
Hi @akgrant43 

Thanks for taking care of this. I will integrate first @guillep support for 64 bits and if it seems to work I will make a release OSSubprocess 3.0. That 3.0 would be able to get loaded into 6.1 with 64 bits. After that, I will make those changes I always wanted (that I need this PR from the VM) and I will make a new release 3.1 but for Pharo 7.0 only (as I need new VM).

**Comment by akgrant43** [comment]
Hi Mariano,

No problem, glad I was able to help.  And thanks to @guillep for his work to.  The OSSubprocess automated tests all pass now on my local machine, and for the first time I've completely loaded up my normal image in 64 bits (SQLite, Glorp, DataFrame, Roassal2, ...)!  It hasn't really been tested yet, but it's a big step in the right direction.

I'm not sure if you're following vm-dev, but just be aware that the primitive names are likely to change based on suggestions from Dave Lewis.  I'll try and remember to let you know here when that happens.

Cheers,
Alistair

**Comment by zecke** [comment]
It made its way into OpensmalltalkVM

**Pull request closed without merging**
