### PR TITLE
Fix issue 13057 copyBits:Fallback:

### PR DESCRIPTION
**Pull request by nicolas-cellier-aka-nice**
Fix issue https://pharo.fogbugz.com/f/cases/13057/DominantColor-brokem
Bug is due to broken fallback code when there is no platform specific accelerated BitBlt
Resolution is trivial, 5 bits per color means a 15 bit mask, that is (1<<15-1)hex -> '16r7FFF' rather than 16r3FFF.

I tested that the pharo VM effectively make the symptom disappear, I get this result:
(Form extent: 80@80 depth: 32) fillWhite dominantColor -> NewColor white

### CODE REVIEW

**Comment by nicolas-cellier-aka-nice** [comment]
Also, this change is already applied on squeak VMMaker and VMMaker.oscog branches.
It's quite safe and SHOULD be applied before releasing 3.0 IMO

**Comment by estebanlm** [comment]
Nicolas, 
you have a conflict merging with head on ./mc/VMMaker-oscog.package/monticello.meta/version 

(is one of the frequent problems in current filetree format... that's why I want to change it... but well, with time).

can you fix it so I can integrate?
(or I can just apply the change to my branch... is tiny enough :P)

**Comment by nicolas-cellier-aka-nice** [comment]
There is no conflict in source code.
Only GitFileTree meta information conflicts, and will always do, unless the pull request come from head.
This is not sustainable...
Fortunately, using https://github.com/ThierryGoubier/GitFileTree-MergeDriver magically solves the GitFileTree mess, you should use it.

**Comment by nicolas-cellier-aka-nice** [comment]
Already fixed by merging of Eliot's branch

**Pull request closed without merging**
