### PR TITLE
updated libgit2 to version 0.22.1

### PR DESCRIPTION
**Pull request by theseion**
I hope everything works. I rebased my stuff ontop of master but didn't test. AFAICT, there shouldn't be any problems though.

### CODE REVIEW

**Comment by estebanlm** [comment]
make[2]: **\* No rule to make target `../results/libssh2.so.1.0.1', needed by ... 

:(

**Comment by theseion** [comment]
crap. I'll test it and see...

**Comment by theseion** [comment]
Ok, I can reproduce the problem on Ubuntu. The build works fine for OS X. I'll try to fix it and let you know,

**Comment by theseion** [comment]
Should now work on both OS X and Linux (tested). Don't know about Windows though...

**Pull request merged**
