### PR TITLE
Fix simulator bitrot

### PR DESCRIPTION
**Pull request by smarr**
:exclamation: This is work in progress, doesn't need to be merged yet.
For the moment, it is just to keep track of things.

With the following code snipped it is possible to run a recent Pharo image on the simulator.

``` Smalltalk
| sim |
InterpreterStackPage initialize.
StackInterpreterSimulator initializeWithOptions: Dictionary new.
sim :=  StackInterpreterSimulator new.
sim openOn: 'Pharo.image'. 
sim openAsMorph.
sim inspect.
1 to: 500 do: [:i |
    World doOneCycleNow.
    sim runForNBytes: 100000 ].
```

### CODE REVIEW

**Comment by smarr** [comment]
After figuring out some of the CMake issues, this generates and builds a proper PharoVM with Bochs simulator plugin on OSX. I did not make any attempt to have cross-platform support. I hope, someone with CMake experience can take it from here.

**Comment by estebanlm** [comment]
cool :)
I can take a look when I come back from holidays.

Esteban

**Comment by smarr** [comment]
Since there was just a discussion on the squeak-dev list, the size of the Bochs plugin might be an issue for distribution. So, I guess, someone needs to check whether it is acceptable in the standard distribution.

http://forum.world.st/working-on-the-All-In-One-tt4746365.html#a4747376
"""- 3 BochsIA34 plugins (one for each aritecture) 
          between 1,3 and 5,3 MB each """

**Comment by camillobruni** [comment]
We ship by default the`.sources` file when using http://get.pharo.org which account for 4.4 and 3.6  MB (compressed) respectively. Hence, I think the Bochs plugin would not make much of difference for the pharo related [downloads](http://files.pharo.org/teststats/2014/02/awstats.awstats.en.html).

**Comment by estebanlm** [comment]
No, it doesnt.
But  I do not think we should ship it by default, since is very specific for vim development. 
Maybe an alternative distribution with the plugin for those interested is better...

Esteban

**Comment by estebanlm** [comment]
I merged manually this changes in the latest trunk, so it should be there now :)

**Comment by smarr** [comment]
Thanks!

**Pull request closed without merging**
