### PR TITLE
Fix issue11359 primitiveStringReplace by applying Newspeak fix

### PR DESCRIPTION
**Pull request by nicolas-cellier-aka-nice**
This enables this snippet to work, not a major fix, but nice to have:
| array1 array2 |
array1 := (1 to: 10) asArray.
array1 replaceFrom: 5 to: 10 with: array1 startingAt: 2.
array2 := (1 to: 10) asArray.
array2 replaceFrom: 5 to: 10 with: array2 copy startingAt: 2.
self assert: array1 = array2
See https://pharo.fogbugz.com/f/cases/11359/Use-memmove-instead-of-memcpy-in-primitives

### CODE REVIEW

**Comment by estebanlm** [comment]
Hi, with your change, I have this results running string tests: 

671 run, 667 passes, 0 skipped, 0 expected failures, 1 failures, 3 errors, 0 unexpected passes
Failures:
CharacterTest>>#testMethodsOfTheClassShouldNotBeRepeatedInItsSuperclasses

Errors:
StringTest>>#testMethodsOfTheClassShouldNotBeRepeatedInItsSuperclasses
WideStringTest>>#testMethodsOfTheClassShouldNotBeRepeatedInItsSuperclasses
SymbolTest>>#testMethodsOfTheClassShouldNotBeRepeatedInItsSuperclasses

**Comment by nicolas-cellier-aka-nice** [comment]
Hi Esteban, thanks for checking.
However, I do not see the relation with this fix...
Beside, those tests pass correctly with my own compiled VM and a tiny bit
out of date Pharo Latest update: #30814

Are you sure that the tests pass with a "regular" VM?
Is this some automated test (jenkins) or something manual?
What should I do to try and reproduce?

2014-04-16 15:44 GMT+02:00 Esteban Lorenzano notifications@github.com:

**Comment by estebanlm** [comment]
Hi, 

yes… I got the failing tests and the first thing I made after is to test it with the vm I’m using (latest) and same not failed. 
Then I tested again your sources… again failing :(

could be something of my build, but I did same steps as in a regular build. 

could again be a problem of using clang instead gcc?

Esteban

**Comment by nicolas-cellier-aka-nice** [comment]
Then it would be usefull to test on linux and windows.
One idea: could it be related to no-cse-follow-jumps?
Did you try and recompile the latest published master 9e648898f53aadb692f2dc95f432daedc449d432?

**Pull request closed without merging**
