### PR TITLE
Fix simulator bitrot

### PR DESCRIPTION
**Pull request by smarr**
These changes enable the StackInterpreterSimulator to load a Pharo 1.2 image, until it hits issues with the BalloonEngine.

The magic expression is:

``` Smalltalk
| sim |
InterpreterStackPage initialize.
StackInterpreterSimulator initializeWithOptions: Dictionary new.
sim :=  StackInterpreterSimulator new.
sim openOn: 'Pharo-1.2.1.image'.
sim openAsMorph.
[ sim run ] fork.
```

### CODE REVIEW

**Comment by philippeback** [comment]
Ah the fork thing is interesting indeed.

---

Philippe Back
Visible Performance Improvements
Mob: +32(0) 478 650 140 | Fax: +32 (0) 70 408 027
Mail:phil@highoctane.be | Web: http://philippeback.eu
Blog: http://philippeback.be | Twitter: @philippeback
Youtube: http://www.youtube.com/user/philippeback/videos

High Octane SPRL
rue cour Boisacq 101 | 1301 Bierges | Belgium

Pharo Consortium Member - http://consortium.pharo.org/
Featured on the Software Process and Measurement Cast -
http://spamcast.libsyn.com
Sparx Systems Enterprise Architect and Ability Engineering EADocX Value
Added Reseller

**Comment by smarr** [comment]
Phil, you had the simulator also almost working?
Any other changes that I might be able to harvest?

**Comment by camillobruni** [comment]
Looks good to me...

Just a minor hint: `'asdfs' asMorph imageForm` works as well ;)

**Comment by philippeback** [comment]
Well, I tried to get things there with Clement but BitBlt gave us headaches.

I can send you my image.

We need this fixed otherwise, we'll stay second class citizens in the VM
development, forced to use the special image of Eliot.

Phil

---

Philippe Back
Dramatic Performance Improvements
Mob: +32(0) 478 650 140 | Fax: +32 (0) 70 408 027
Mail:phil@highoctane.be | Web: http://philippeback.eu
Blog: http://philippeback.be | Twitter: @philippeback
Youtube: http://www.youtube.com/user/philippeback/videos

High Octane SPRL
rue cour Boisacq 101 | 1301 Bierges | Belgium

Featured on the Software Process and Measurement Cast
http://spamcast.libsyn.com
Sparx Systems Enterprise Architect and Ability Engineering EADocX Value
Added Reseller

**Comment by philippeback** [comment]
My stance was:

| vm |
StackInterpreterSimulator initializeWithOptions: Dictionary new.
vm := StackInterpreterSimulator new.
InterpreterStackPage initialize.
vm openOn: 'C:\MinGW\msys\1.0\home\User\pharo\pharo.image'.
vm openAsMorph.
vm run.

vm := nil.
Smalltalk garbageCollect.

---

Philippe Back
Dramatic Performance Improvements
Mob: +32(0) 478 650 140 | Fax: +32 (0) 70 408 027
Mail:phil@highoctane.be | Web: http://philippeback.eu
Blog: http://philippeback.be | Twitter: @philippeback
Youtube: http://www.youtube.com/user/philippeback/videos

High Octane SPRL
rue cour Boisacq 101 | 1301 Bierges | Belgium

Featured on the Software Process and Measurement Cast
http://spamcast.libsyn.com
Sparx Systems Enterprise Architect and Ability Engineering EADocX Value
Added Reseller

**Comment by smarr** [comment]
@philippeback either the image, or if you got, a change set that would be helpful. I didn't yet run into obviously BitBlt related issues. There is currently something, also triggering many GCs, so that the display doesn't come up properly. That's with Pharo 1.4 and newer. A Pharo 1.2 image loads and renders already. But then hits on bitrot in all kind of plugins.

**Comment by smarr** [comment]
@camillobruni, will apply your change. Merging can probably wait until the pull request is more complete.

**Comment by estebanlm** [comment]
s**t I merged :P 
sorry I did not read the last comment.

**Pull request merged**
