### PR TITLE
Spur64

### PR DESCRIPTION
**Pull request by bencoman**
Opening discussion on adding new primitives for introduction of OwnedLock into the Pharo image with
Issue 17373 (https://pharo.fogbugz.com/default.asp?17373)

```
(207 primitiveOwnedLockStrictRelease)
(208 primitiveOwnedLockTryAcquire)
(209 primitiveOwnedLockWaitAcquire)
```

Matches SLICE-Issue-17373-Mutex-should-be-based-on-VM-primitives-and-implement-critical-methods-from-Semaphore--BenComan.14

It is hoped these can be considered that these don't impact existing code, and thus fairly isolated and low risk on the rest of the system, and possibly make it into Pharo 5 to idle mostly out of site, but possible for people to try out.

### CODE REVIEW

**Comment by estebanlm** [comment]
not sure this is the good way to provide such additions... I think is better to add them to VMMaker.oscog in Eliot's repository (this repository acts just as a mirror in case of VMMaker package). 
Of course, I can do it for you, but then you will need to wait a couple of days :smile:

**Comment by bencoman** [comment]
Cool, I can do that.  The workflow is a journey of discovery ;)

Doing it on github was also (maybe) a way for Dennis to build and trial the
VM to run the slice I submitted to Pharo5Inbox sooner.
cheers -ben

On Mon, Feb 22, 2016 at 7:06 PM, Esteban Lorenzano <notifications@github.com

**Comment by estebanlm** [comment]
so, nothing happened in Eliot side but he agreed to add them... so I suppose I can add them and commit to VMMaker repository. 
Is that ok?

**Comment by dionisiydk** [comment]
I wish it be Ok :)

**Comment by bencoman** [comment]
sorry I've been distracted trying to set up a hosted minecraft server for
my kids.  I have something to present. Give me a couple of days to get back
to it to bring it together for review.
cheers -ben

On Mon, Mar 21, 2016 at 11:15 PM, Denis Kudriashov <notifications@github.com

**Pull request closed without merging**
